# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import logging



from PyQt5 import QtCore, QtGui, QtWidgets
from acquisition import MyMplCanvas, Ui_Table_Window,Connection

class Ui_TestWindow(object):
    def __init__(self, MainWindow,config,conn,ui_table_window):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(337, 235)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.mpl_canvas = self.mplCanvas_widget = MyMplCanvas(parent=None, config=config, conn=conn, table_window=ui_table_window)
        self.gridLayout_2.addWidget(self.mpl_canvas,0,0,1,1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 337, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    config = {'sensors': [['TC', '101'], ['TC', '102'], ['TC', '103']], 'scans': 150, 'delay': 0.5, 'file': {'type': 'xlsx', 'filename': 'test'}}
    conn = Connection(None,config)
    ui = Ui_TestWindow(MainWindow,config,conn,None)
    MainWindow.show()
    sys.exit(app.exec_())
